// Generated from parity/reference/labelshop/probe-08-install-list.txt + probe-10-install-filter.txt
// （真机「安装 LabelShop 打印机」对话框的取证产物）。请勿手改；改动取证后重跑：
//   node app/scripts/generate-printer-catalog.cjs

export interface PrinterCatalogEntry {
  id: string
  /** 真机列表里显示的名称，例如 "Gprinter GPL-N (203 dpi)" */
  name: string
  /** 名称里的品牌英文段，例如 "Gprinter" */
  brand: string
  /** 真机品牌过滤下拉里的标签，例如 "佳博 (Gprinter)" */
  brandLabel: string
  /** 型号/指令集段，例如 "GPL" */
  model: string
  /** "-N" 后的后缀，例如 "N" */
  commandSet: string
  dpi: number
}

/** 真机品牌过滤下拉：全部 + 38 个品牌 */
export const PRINTER_BRAND_FILTER: readonly string[] = ["全部","斑马 (Zebra)","TSC / Zenpert","东芝泰格 (TEC)","普印力 (PRINTRONIX)","佐藤 (SATO)","实诺锐 (SONARAY)","川步 (Zgtrumb)","实达 (START)","佳博 (Gprinter)","雷丹 (Leden)","打印猿 (PrintMan)","中盈科技 (ZhongYing)","维庭 (Weiting)","资江 (ZIJIANG)","斯普瑞特 (SPRT)","成为 (CHAINWAY)","奥莱新创 (AOLXC)","科诚 (GoDEX)","立象 (Argox)","普贴 (PUTY)","映美 (Jolimark)","艾美多 (AMYDOR)","映之美 (iZM)","芝柯 (ZICOX)","Honeywell","容大 (RONGTA)","腾坤 (Towercode)","爱立熊 (Alison)","致明兴 (ZMIN)","瑞工 (REGO)","博思得 (POSTEK)","启锐/爱印 (QIRUI/IPRT)","美松 (MASUNG)","芯烨 (Xprinter)","汉印 (HPRT)","爱印互联 (AIYIN)","新北洋 (SNBC)","济强 (JQTEK)"]

/** 真机「可安装的打印机」列表的 125 行 */
export const PRINTER_CATALOG: readonly PrinterCatalogEntry[] = [
  { id: "ls-001", name: "Gprinter GPL-N (203 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "GPL", commandSet: "N", dpi: 203 },
  { id: "ls-002", name: "Gprinter GPL-N (300 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "GPL", commandSet: "N", dpi: 300 },
  { id: "ls-003", name: "Gprinter GPLZ-N (203 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "GPLZ", commandSet: "N", dpi: 203 },
  { id: "ls-004", name: "Gprinter GPLZ-N (300 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "GPLZ", commandSet: "N", dpi: 300 },
  { id: "ls-005", name: "Gprinter ESCPOS-N (200 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "ESCPOS", commandSet: "N", dpi: 200 },
  { id: "ls-006", name: "Gprinter ESCPOS-N (200 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "ESCPOS", commandSet: "N", dpi: 200 },
  { id: "ls-007", name: "Gprinter GPLZ-N (203 dpi)", brand: "Gprinter", brandLabel: "佳博 (Gprinter)", model: "GPLZ", commandSet: "N", dpi: 203 },
  { id: "ls-008", name: "Leden APL-N (203 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APL", commandSet: "N", dpi: 203 },
  { id: "ls-009", name: "Leden APL-N (300 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APL", commandSet: "N", dpi: 300 },
  { id: "ls-010", name: "Leden APL-N (600 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APL", commandSet: "N", dpi: 600 },
  { id: "ls-011", name: "Leden RFID-N (203 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "RFID", commandSet: "N", dpi: 203 },
  { id: "ls-012", name: "Leden RFID-N (300 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "RFID", commandSet: "N", dpi: 300 },
  { id: "ls-013", name: "Leden RFID-N (600 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "RFID", commandSet: "N", dpi: 600 },
  { id: "ls-014", name: "Leden APLZ-N (203 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APLZ", commandSet: "N", dpi: 203 },
  { id: "ls-015", name: "Leden APLZ-N (300 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APLZ", commandSet: "N", dpi: 300 },
  { id: "ls-016", name: "Leden APLZ-N (600 dpi)", brand: "Leden", brandLabel: "雷丹 (Leden)", model: "APLZ", commandSet: "N", dpi: 600 },
  { id: "ls-017", name: "TOSHIBA-TEC TPCL-N (203 dpi)", brand: "TOSHIBA-TEC", brandLabel: "东芝泰格 (TEC)", model: "TPCL", commandSet: "N", dpi: 203 },
  { id: "ls-018", name: "TOSHIBA-TEC TPCL-N (300 dpi)", brand: "TOSHIBA-TEC", brandLabel: "东芝泰格 (TEC)", model: "TPCL", commandSet: "N", dpi: 300 },
  { id: "ls-019", name: "TOSHIBA-TEC TPCL-N (600 dpi)", brand: "TOSHIBA-TEC", brandLabel: "东芝泰格 (TEC)", model: "TPCL", commandSet: "N", dpi: 600 },
  { id: "ls-020", name: "TSC TSPL-N (203 dpi)", brand: "TSC", brandLabel: "TSC / Zenpert", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-021", name: "TSC TSPL-N (300 dpi)", brand: "TSC", brandLabel: "TSC / Zenpert", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-022", name: "TSC TSPL-N (600 dpi)", brand: "TSC", brandLabel: "TSC / Zenpert", model: "TSPL", commandSet: "N", dpi: 600 },
  { id: "ls-023", name: "Zenpert TSPL-N (203 dpi)", brand: "Zenpert", brandLabel: "TSC / Zenpert", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-024", name: "Zenpert TSPL-N (300 dpi)", brand: "Zenpert", brandLabel: "TSC / Zenpert", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-025", name: "Zebra ZPL-N (203 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "ZPL", commandSet: "N", dpi: 203 },
  { id: "ls-026", name: "Zebra ZPL-N (300 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "ZPL", commandSet: "N", dpi: 300 },
  { id: "ls-027", name: "Zebra ZPL-N (600 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "ZPL", commandSet: "N", dpi: 600 },
  { id: "ls-028", name: "Zebra CPCL-N (203 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-029", name: "Zebra EPL-N (203 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "EPL", commandSet: "N", dpi: 203 },
  { id: "ls-030", name: "Zebra EPL-N (300 dpi)", brand: "Zebra", brandLabel: "斑马 (Zebra)", model: "EPL", commandSet: "N", dpi: 300 },
  { id: "ls-031", name: "SATO CLNX-N (203 dpi)", brand: "SATO", brandLabel: "佐藤 (SATO)", model: "CLNX", commandSet: "N", dpi: 203 },
  { id: "ls-032", name: "SATO CLNX-N (305 dpi)", brand: "SATO", brandLabel: "佐藤 (SATO)", model: "CLNX", commandSet: "N", dpi: 305 },
  { id: "ls-033", name: "SATO CLNX-N (609 dpi)", brand: "SATO", brandLabel: "佐藤 (SATO)", model: "CLNX", commandSet: "N", dpi: 609 },
  { id: "ls-034", name: "SONARAY ZPL-N (203 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "ZPL", commandSet: "N", dpi: 203 },
  { id: "ls-035", name: "SONARAY ZPL-N (300 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "ZPL", commandSet: "N", dpi: 300 },
  { id: "ls-036", name: "SONARAY ZPL-N (600 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "ZPL", commandSet: "N", dpi: 600 },
  { id: "ls-037", name: "SONARAY TSPL-N (203 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-038", name: "SONARAY TSPL-N (300 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-039", name: "SONARAY TSPL-N (600 dpi)", brand: "SONARAY", brandLabel: "实诺锐 (SONARAY)", model: "TSPL", commandSet: "N", dpi: 600 },
  { id: "ls-040", name: "ZY ESCPOS-N (203 dpi)", brand: "ZY", brandLabel: "中盈科技 (ZhongYing)", model: "ESCPOS", commandSet: "N", dpi: 203 },
  { id: "ls-041", name: "Weiting CPCL-N (203 dpi)", brand: "Weiting", brandLabel: "维庭 (Weiting)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-042", name: "ZIJIANG TSPL-N (203 dpi)", brand: "ZIJIANG", brandLabel: "资江 (ZIJIANG)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-043", name: "SPRT TSPL-N (203 dpi)", brand: "SPRT", brandLabel: "斯普瑞特 (SPRT)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-044", name: "SPRT TL54-N (203 dpi)", brand: "SPRT", brandLabel: "斯普瑞特 (SPRT)", model: "TL54", commandSet: "N", dpi: 203 },
  { id: "ls-045", name: "GoDEX EZPL-N (203 dpi)", brand: "GoDEX", brandLabel: "科诚 (GoDEX)", model: "EZPL", commandSet: "N", dpi: 203 },
  { id: "ls-046", name: "GoDEX EZPL-N (300 dpi)", brand: "GoDEX", brandLabel: "科诚 (GoDEX)", model: "EZPL", commandSet: "N", dpi: 300 },
  { id: "ls-047", name: "GoDEX EZPL-N (600 dpi)", brand: "GoDEX", brandLabel: "科诚 (GoDEX)", model: "EZPL", commandSet: "N", dpi: 600 },
  { id: "ls-048", name: "PUTY TSPL-N (203 dpi)", brand: "PUTY", brandLabel: "普贴 (PUTY)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-049", name: "PUTY TSPL-N (300 dpi)", brand: "PUTY", brandLabel: "普贴 (PUTY)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-050", name: "SNBC BPLA-U (203 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "U", dpi: 203 },
  { id: "ls-051", name: "SNBC BPLA-U (300 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "U", dpi: 300 },
  { id: "ls-052", name: "SNBC BPLA-L (203 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "L", dpi: 203 },
  { id: "ls-053", name: "SNBC BPLA-L (300 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "L", dpi: 300 },
  { id: "ls-054", name: "SNBC BPLA-E (203 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "E", dpi: 203 },
  { id: "ls-055", name: "SNBC BPLA-E (300 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLA", commandSet: "E", dpi: 300 },
  { id: "ls-056", name: "SNBC BPLZ-N (203 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLZ", commandSet: "N", dpi: 203 },
  { id: "ls-057", name: "SNBC BPLZ-N (300 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLZ", commandSet: "N", dpi: 300 },
  { id: "ls-058", name: "SNBC BPLE-N (203 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLE", commandSet: "N", dpi: 203 },
  { id: "ls-059", name: "SNBC BPLE-N (300 dpi)", brand: "SNBC", brandLabel: "新北洋 (SNBC)", model: "BPLE", commandSet: "N", dpi: 300 },
  { id: "ls-060", name: "HPRT TSPL-N (203 dpi)", brand: "HPRT", brandLabel: "汉印 (HPRT)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-061", name: "HPRT TSPL-N (300 dpi)", brand: "HPRT", brandLabel: "汉印 (HPRT)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-062", name: "HPRT ZPL-N (203 dpi)", brand: "HPRT", brandLabel: "汉印 (HPRT)", model: "ZPL", commandSet: "N", dpi: 203 },
  { id: "ls-063", name: "HPRT ZPL-N (300 dpi)", brand: "HPRT", brandLabel: "汉印 (HPRT)", model: "ZPL", commandSet: "N", dpi: 300 },
  { id: "ls-064", name: "HPRT CPCL-N (203 dpi)", brand: "HPRT", brandLabel: "汉印 (HPRT)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-065", name: "JQTEK CPCL-N (203 dpi)", brand: "JQTEK", brandLabel: "济强 (JQTEK)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-066", name: "JQTEK JPL-N (203 dpi)", brand: "JQTEK", brandLabel: "济强 (JQTEK)", model: "JPL", commandSet: "N", dpi: 203 },
  { id: "ls-067", name: "JQTEK ESCPOS-80-N (203 dpi)", brand: "JQTEK", brandLabel: "济强 (JQTEK)", model: "ESCPOS-80", commandSet: "N", dpi: 203 },
  { id: "ls-068", name: "AIYIN POS-58-N (203 dpi)", brand: "AIYIN", brandLabel: "爱印互联 (AIYIN)", model: "POS-58", commandSet: "N", dpi: 203 },
  { id: "ls-069", name: "AIYIN POS-80-N (203 dpi)", brand: "AIYIN", brandLabel: "爱印互联 (AIYIN)", model: "POS-80", commandSet: "N", dpi: 203 },
  { id: "ls-070", name: "AIYIN CPCL-N (203 dpi)", brand: "AIYIN", brandLabel: "爱印互联 (AIYIN)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-071", name: "QIRUI TSPL-N (203 dpi)", brand: "QIRUI", brandLabel: "启锐/爱印 (QIRUI/IPRT)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-072", name: "QIRUI CPCL-N (203 dpi)", brand: "QIRUI", brandLabel: "启锐/爱印 (QIRUI/IPRT)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-073", name: "QIRUI TSPL-N (300 dpi)", brand: "QIRUI", brandLabel: "启锐/爱印 (QIRUI/IPRT)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-074", name: "Alison A6-N", brand: "Alison", brandLabel: "爱立熊 (Alison)", model: "A6", commandSet: "N", dpi: 0 },
  { id: "ls-075", name: "Alison A6-N", brand: "Alison", brandLabel: "爱立熊 (Alison)", model: "A6", commandSet: "N", dpi: 0 },
  { id: "ls-076", name: "REGO POS-58-N (203 dpi)", brand: "REGO", brandLabel: "瑞工 (REGO)", model: "POS-58", commandSet: "N", dpi: 203 },
  { id: "ls-077", name: "REGO POS-80-N (203 dpi)", brand: "REGO", brandLabel: "瑞工 (REGO)", model: "POS-80", commandSet: "N", dpi: 203 },
  { id: "ls-078", name: "REGO CPCL-N (203 dpi)", brand: "REGO", brandLabel: "瑞工 (REGO)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-079", name: "Postek PPLE-N (203 dpi)", brand: "Postek", brandLabel: "博思得 (POSTEK)", model: "PPLE", commandSet: "N", dpi: 203 },
  { id: "ls-080", name: "Postek PPLE-N (300 dpi)", brand: "Postek", brandLabel: "博思得 (POSTEK)", model: "PPLE", commandSet: "N", dpi: 300 },
  { id: "ls-081", name: "Postek PPLE-N (600 dpi)", brand: "Postek", brandLabel: "博思得 (POSTEK)", model: "PPLE", commandSet: "N", dpi: 600 },
  { id: "ls-082", name: "Jolimark POS-58-N (203 dpi)", brand: "Jolimark", brandLabel: "映美 (Jolimark)", model: "POS-58", commandSet: "N", dpi: 203 },
  { id: "ls-083", name: "Jolimark POS-80-N (203 dpi)", brand: "Jolimark", brandLabel: "映美 (Jolimark)", model: "POS-80", commandSet: "N", dpi: 203 },
  { id: "ls-084", name: "Jolimark CLP-180-N (203 dpi)", brand: "Jolimark", brandLabel: "映美 (Jolimark)", model: "CLP-180", commandSet: "N", dpi: 203 },
  { id: "ls-085", name: "AMYDOR AMD-N (203 dpi)", brand: "AMYDOR", brandLabel: "艾美多 (AMYDOR)", model: "AMD", commandSet: "N", dpi: 203 },
  { id: "ls-086", name: "AMYDOR AMD-N (300 dpi)", brand: "AMYDOR", brandLabel: "艾美多 (AMYDOR)", model: "AMD", commandSet: "N", dpi: 300 },
  { id: "ls-087", name: "AMYDOR AMD-N (600 dpi)", brand: "AMYDOR", brandLabel: "艾美多 (AMYDOR)", model: "AMD", commandSet: "N", dpi: 600 },
  { id: "ls-088", name: "ZMIN EPL-N (203 dpi)", brand: "ZMIN", brandLabel: "致明兴 (ZMIN)", model: "EPL", commandSet: "N", dpi: 203 },
  { id: "ls-089", name: "ZMIN EPL-N (300 dpi)", brand: "ZMIN", brandLabel: "致明兴 (ZMIN)", model: "EPL", commandSet: "N", dpi: 300 },
  { id: "ls-090", name: "iZM ID221-CPCL-N (203 dpi)", brand: "iZM", brandLabel: "映之美 (iZM)", model: "ID221-CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-091", name: "iZM ID421-CPCL-N (203 dpi)", brand: "iZM", brandLabel: "映之美 (iZM)", model: "ID421-CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-092", name: "ZICOX CPCL-58-N (203 dpi)", brand: "ZICOX", brandLabel: "芝柯 (ZICOX)", model: "CPCL-58", commandSet: "N", dpi: 203 },
  { id: "ls-093", name: "ZICOX CPCL-80-N (203 dpi)", brand: "ZICOX", brandLabel: "芝柯 (ZICOX)", model: "CPCL-80", commandSet: "N", dpi: 203 },
  { id: "ls-094", name: "ZICOX CPCL-110-N (203 dpi)", brand: "ZICOX", brandLabel: "芝柯 (ZICOX)", model: "CPCL-110", commandSet: "N", dpi: 203 },
  { id: "ls-095", name: "ZICOX POS-110-N (203 dpi)", brand: "ZICOX", brandLabel: "芝柯 (ZICOX)", model: "POS-110", commandSet: "N", dpi: 203 },
  { id: "ls-096", name: "Honeywell POS-80-N (203 dpi)", brand: "Honeywell", brandLabel: "Honeywell", model: "POS-80", commandSet: "N", dpi: 203 },
  { id: "ls-097", name: "Honeywell FingerPrint (203 dpi)", brand: "Honeywell", brandLabel: "Honeywell", model: "FingerPrint", commandSet: "", dpi: 203 },
  { id: "ls-098", name: "RONGTA TSPL-N (203 dpi)", brand: "RONGTA", brandLabel: "容大 (RONGTA)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-099", name: "Towercode TSPL-N (203 dpi)", brand: "Towercode", brandLabel: "腾坤 (Towercode)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-100", name: "Zgtrumb TSPL-N (203 dpi)", brand: "Zgtrumb", brandLabel: "川步 (Zgtrumb)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-101", name: "Zgtrumb TSPL-N (300 dpi)", brand: "Zgtrumb", brandLabel: "川步 (Zgtrumb)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-102", name: "PrintMan TSPL-N (203 dpi)", brand: "PrintMan", brandLabel: "打印猿 (PrintMan)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-103", name: "PrintMan CPCL-N (203 dpi)", brand: "PrintMan", brandLabel: "打印猿 (PrintMan)", model: "CPCL", commandSet: "N", dpi: 203 },
  { id: "ls-104", name: "START SPLZ-N (203 dpi)", brand: "START", brandLabel: "实达 (START)", model: "SPLZ", commandSet: "N", dpi: 203 },
  { id: "ls-105", name: "START SPLZ-N (300 dpi)", brand: "START", brandLabel: "实达 (START)", model: "SPLZ", commandSet: "N", dpi: 300 },
  { id: "ls-106", name: "START SPLZ-N (600 dpi)", brand: "START", brandLabel: "实达 (START)", model: "SPLZ", commandSet: "N", dpi: 600 },
  { id: "ls-107", name: "Printronix PGL-N (203 dpi)", brand: "Printronix", brandLabel: "普印力 (PRINTRONIX)", model: "PGL", commandSet: "N", dpi: 203 },
  { id: "ls-108", name: "Printronix PGL-N (300 dpi)", brand: "Printronix", brandLabel: "普印力 (PRINTRONIX)", model: "PGL", commandSet: "N", dpi: 300 },
  { id: "ls-109", name: "Printronix PGL-N (600 dpi)", brand: "Printronix", brandLabel: "普印力 (PRINTRONIX)", model: "PGL", commandSet: "N", dpi: 600 },
  { id: "ls-110", name: "CHAINWAY TSPL-N (203 dpi)", brand: "CHAINWAY", brandLabel: "成为 (CHAINWAY)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-111", name: "CHAINWAY TSPL-N (300 dpi)", brand: "CHAINWAY", brandLabel: "成为 (CHAINWAY)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-112", name: "AOLXC ESCPOS-N (203 dpi)", brand: "AOLXC", brandLabel: "奥莱新创 (AOLXC)", model: "ESCPOS", commandSet: "N", dpi: 203 },
  { id: "ls-113", name: "AOLXC ESCPOS-N (300 dpi)", brand: "AOLXC", brandLabel: "奥莱新创 (AOLXC)", model: "ESCPOS", commandSet: "N", dpi: 300 },
  { id: "ls-114", name: "AOLXC ESCPOS-N (600 dpi)", brand: "AOLXC", brandLabel: "奥莱新创 (AOLXC)", model: "ESCPOS", commandSet: "N", dpi: 600 },
  { id: "ls-115", name: "MASUNG MTPL-N (203 dpi)", brand: "MASUNG", brandLabel: "美松 (MASUNG)", model: "MTPL", commandSet: "N", dpi: 203 },
  { id: "ls-116", name: "MASUNG MTPL-N (300 dpi)", brand: "MASUNG", brandLabel: "美松 (MASUNG)", model: "MTPL", commandSet: "N", dpi: 300 },
  { id: "ls-117", name: "XPrinter TSPL-N (203 dpi)", brand: "XPrinter", brandLabel: "芯烨 (Xprinter)", model: "TSPL", commandSet: "N", dpi: 203 },
  { id: "ls-118", name: "XPrinter TSPL-N (300 dpi)", brand: "XPrinter", brandLabel: "芯烨 (Xprinter)", model: "TSPL", commandSet: "N", dpi: 300 },
  { id: "ls-119", name: "XPrinter TSPL-N (600 dpi)", brand: "XPrinter", brandLabel: "芯烨 (Xprinter)", model: "TSPL", commandSet: "N", dpi: 600 },
  { id: "ls-120", name: "Argox PPLA-N (203 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLA", commandSet: "N", dpi: 203 },
  { id: "ls-121", name: "Argox PPLA-N (300 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLA", commandSet: "N", dpi: 300 },
  { id: "ls-122", name: "Argox PPLA-N (600 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLA", commandSet: "N", dpi: 600 },
  { id: "ls-123", name: "Argox PPLB-N (203 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLB", commandSet: "N", dpi: 203 },
  { id: "ls-124", name: "Argox PPLB-N (300 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLB", commandSet: "N", dpi: 300 },
  { id: "ls-125", name: "Argox PPLB-N (600 dpi)", brand: "Argox", brandLabel: "立象 (Argox)", model: "PPLB", commandSet: "N", dpi: 600 }
]
